export const ChartConstants = {
    GET_POWER_DATA_REQUEST: "GET_POWER_DATA_REQUEST",
    GET_POWER_DATA_SUCCESS: "GET_POWER_DATA_SUCCESS",
    GET_POWER_DATA_FAILE: "GET_POWER_DATA_FAILE",
    
    GET_CURRENT_DATA_REQUEST: "GET_CURRENT_DATA_REQUEST",
    GET_CURRENT_DATA_SUCCESS: "GET_CURRENT_DATA_SUCCESS",
    GET_CURRENT_DATA_FAILE: "GET_CURRENT_DATA_FAILE",

    GET_VOLTAGE_DATA_REQUEST: "GET_VOLTAGE_DATA_REQUEST",
    GET_VOLTAGE_DATA_SUCCESS: "GET_VOLTAGE_DATA_SUCCESS",
    GET_VOLTAGE_DATA_FAILE: "GET_VOLTAGE_DATA_FAILE",

}