export const userConstant = {
    GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
    GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",

    DELETE_USER_REQUEST: "DELETE_DELETE_USER_REQUEST",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

    EDIT_USER_REQUEST: "EDIT_USER_REQUEST",
    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_FAILURE: "EDIT_USER_FAILURE",

    GET_DETAIL_USER_REQUEST: "GET_DETAIL_USER_REQUEST",
    GET_DETAIL_USER_SUCCESS: "GET_DETAIL_USER_SUCCESS",
    GET_DETAIL_USER_FAILURE: "GET_DETAIL_USER_FAILURE"


}